# "namespace" omitted since ClusterRoles are not namespaced

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aks-cluster-readonly-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aks-cluster-readonly-rolebinding

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aks-cluster-readonly-role

subjects:
- kind: Group
  #name: groupObjectId # Your Azure AD Group Object ID: aksreadonly
  name: "e8f709f7-4029-4fdb-b786-d0af29445fc9"  
  apiGroup: rbac.authorization.k8s.io




# Step-02: Create AD Group, Role Assignment and User
# # Get Azure AKS Cluster Id
# AKS_CLUSTER_ID=$(az aks show --resource-group aks-rg3 --name aksdemo3 --query id -o tsv)
# echo $AKS_CLUSTER_ID

# # Create Azure AD Group
# AKS_READONLY_GROUP_ID=$(az ad group create --display-name aksreadonly --mail-nickname aksreadonly --query objectId -o tsv)    
# echo $AKS_READONLY_GROUP_ID

# # Create Role Assignment