# Create a cluste with 3 nodes 
# add a label on one node, example k label node <node name> disktype=ssh
# create pod with below 


apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test

spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    disktype: ssd

